catch gh::gh_token() error when no PAT is set
* the gh docs are not very clear on this
* it appears that if you have cached github login information
  but no PAT then you will get an error of the form:

Error: GitHub PAT must have one of these forms:
  * 40 hexadecimal digits (older PATs)
  * A 'ghp_' prefix followed by 36 to 251 more characters (newer PATs)